spring.application.name=productos

# Configuración de la base de datos MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/productos?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=my-secret-pw
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de JPA / Hibernate
# 'none' delega el manejo del esquema completamente a Flyway
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Flyway - Migraciones de base de datos
spring.flyway.enabled=true
spring.flyway.repair=true